#!/bin/bash
# simple collect data from linux system amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
# and send to the timeseries databases
# cooking by dariusz@porczynski.net mishmash for now ... but working :)
# main goals: POSIX/GNU/Linux portability, simple and lightweight, used BASH only with a few standard
# dependiences

# parse config file
config="/etc/ustat.conf"
. <(sed -nE "/^\[\[outputs\.influxdb\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf | grep database | sed 's/ *= */=/g')
influxdb_database=$database
. <(sed -nE "/^\[\[outputs\.influxdb\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf | grep urls | sed 's/\[//g' | sed 's/\]//g' | sed 's/ *= */=/g')
influxdb_host=$urls
. <(sed -nE "/^\[agent\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf | sed 's/ *= */=/g' | grep " interval" | sed 's/ *= */=/g')
interval=$interval
. <(sed -nE "/^\[\[inputs\.net\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf | grep "interfaces" | sed 's/ *= */=/g' | sed 's/\[/\(/g' | sed 's/\]/\)/g' | sed 's/,/ /g')
for network_interface in ${interfaces[@]}; do
  echo $interface
done

# . /etc/ustat.conf
# database based on mac address for now, TODO: crypted, based on UUID and/or hardware IDs
read_eth0_mac_address=`cat /sys/class/net/eth0/address | tr ':' ' ' | tr '\n' ' ' | sed 's/[[:space:]]//g'`

initialize_matrics () {
  $read_eth0_mac_address
#  /usr/share/opentsdb/bin/tsdb mkmetric $eth0_mac_address.proc.loadavg.1m
#  /usr/share/opentsdb/bin/tsdb mkmetric $eth0_mac_address.proc.loadavg.5m
#  /usr/share/opentsdb/bin/tsdb mkmetric $eth0_mac_address.proc.loadavg.15m
}

read_proc_loadavg () {
  eth0_mac_address=$1
  awk -v now=`date +%s` -v host=`hostname` \
  '{ print "put '$eth0_mac_address'.proc.loadavg.1m " now " " $1 " host=" host;
  print "put '$eth0_mac_address'.proc.loadavg.5m " now " " $2 " host=" host;
  print "put '$eth0_mac_address'.proc.loadavg.15m " now " " $3 " host=" host; }' /proc/loadavg
}

read_proc_load () {
  now_timestamp=`date +%s`
  awk '{ print $1 }' /proc/loadavg
#  proc_loadawg_1=(awk '{ print $1 }' /proc/loadavg)
#  echo $proc_loadavg_1
}

read_network_stats () {
  timestamp=`date +%s`
  rx=$(grep $1 /proc/net/dev | awk '{print $2}')
  tx=$(grep $1 /proc/net/dev | awk '{print $10}')
  network_usage=$(cat /proc/net/dev | grep "$1:" | cut -f2 -d':' | awk '{print $1}')
  return
}

show_databases () {
  curl -G "$influxdb_host/query?pretty=true" --data-urlencode 'q=SHOW DATABASES'
}

read_database () {
#  echo "read influxdb_database at $influxdb_host/query?db=$influxdb_database&pretty=true"
  curl -G "$influxdb_host/query?db=$influxdb_database" --data-urlencode 'q=SELECT * FROM "$indluxdb_database"'
}

create_database () {
  echo "create database $influxdb_database"
#  curl -XPOST "$influxdb_host/query" -s --data-urlencode 'q=CREATE DATABASE "$influxdb_database"'
  curl -XPOST "$influxdb_host/query" -s --data-urlencode "q=CREATE DATABASE $influxdb_database"
}

drop_database () {
  echo "drop database $influxdb_database"
  curl -XPOST "$influxdb_host/query" -s --data-urlencode "q=DROP DATABASE $influxdb_database"
}

write_a_point_to_influxdb () {
  measurement="$1"
  rx="$2"
  curl -i XPOST "$influxdb_host/write?db=$influxdb_database&precision=s" --data-binary "$measurement,interface=$network_interface rx=$rx $timestamp"
}

write_loop () {
  while true; do
    curl -i XPOST "$influxdb_host/write?db=h3test&precision=s" --data-binary "$influxdb_database,interface=$network_interface rx=$rx $timestamp"
    sleep $interval
    echo "done..."
  done
}

ustat_help () {
  echo -e "usage: ustat <-option>\n\
  -b \t\t\t verbose\n\
  -c \t\t\t read_database\n\
  -d \t\t\t drop_database\n\
  -i [database] \t database name\n\
  -o [network_interface] \t network interface eg. -o eth0\n\
  -p \t\t\t read_proc_load\n\
  -r \t\t\t read_database\n\
  -s \t\t\t show_databases\n\
  -t [interval] \t interval in seconds eg. -t 5\n\
  -w \t\t\t write a point to influxdb database\n\
"
}

while getopts 'b c d h i: o p r s t: w' opt
do
  case "${opt}" in
    b ) _VERBOSE="true"
    ;;
    c ) create_database
    ;;
    d ) drop_database
    ;;
    h ) ustat_help
    ;;
    i ) influxdb_database="$OPTARG"; echo "influxdb_database=$OPTARG"
    ;;
    o ) read_network_stats $network_interface; echo -e "timestamp=$timestamp rx=$rx tx=$tx"
    ;;
    p ) read_proc_load
    ;;
    r ) read_database
    ;;
    s ) show_databases
    ;;
    t ) interval="$OPTARG"
    ;;
    w )
    while true; do
      read_network_stats $network_interface
      echo -e "timestamp=$timestamp rx=$rx tx=$tx"
      write_a_point_to_influxdb $influxdb_database $rx
      sleep $interval
    done
    ;;
    :) echo "Option -$OPTARG requires an argument." >&2
    ;;
    * )  ustat_help; exit 0
    ;;
  esac
done
shift $((OPTIND-1))
